# 67.前端异常示例.68
## <a name="index"></a> 目录
- [引子](#start)
- [基础知识点](#basic)
- [EvalError](#eval)
- [RangeError](#range)
- [SyntaxError](#syntax)
- [TypeError](#type)
- [URIError](#uri)
- [AggregateError](#aggregate)
- [资源加载异常](#load)
- [接口请求异常](#api)
- [Script error.](#script)
- [参考资料](#reference)


## <a name="start"></a> 引子
在 [前端异常类型及捕获方式][url-blog-53] 之后，尝试了自己去封装一下，然后去看了 [sentry][url-github-2] 的源码，发现之前的那篇只是一个概括，当采集的时候，需要更加细致的解析，接下来看看各种异常具体是什么样的。

## <a name="basic"></a> 基础知识点
前端异常一定会接触到 `Error` 对象，先来简单的了解一下。

错误的类型：
- Error ： 基类型，其它错误类型都是继承自该类型。
- EvalError ： 使用 `eval()` 函数而发生异常时抛出。
- RangeError ： 数值超出相应有效范围时的异常。
- ReferenceError ： 访问无效的引用的异常。
- SyntaxError ： 语法错误的异常。
- TypeError ： 变量或参数不是一个有效类型的异常。
- URIError ： `encodeURI()` 或 `decodeURI()` 传入无效参数的异常。
- AggregateError ： 一个操作导致多个异常需要报告，例如 `Promise.any()` 。
- InternalError ： JavaScript 引擎内部抛出的错误，这个还没有标准化。


实例共有的标准属性：
- message ： 异常信息。
- name ： 异常名称。

实例共有的非标准属性：
- description ： 微软的非标准属性，类似 message 。
- number ： 微软的非标准属性，异常数字。
- fileName ： Mozilla 的非标准属性，异常产生所在文件的路径。
- lineNumber ： Mozilla 的非标准属性，异常产生所在文件的行数。
- columnNumber ： Mozilla 的非标准属性，异常产生所在文件的列数。
- stack ： Mozilla 的非标准属性，堆栈跟踪。

下面看看每种类型的示例。（暂没有考虑框架）

以下示例环境：
- Chrome ：86.0.4240.198（正式版本） (x86_64)。
- 使用 nginx 启动了一个本地服务，原生 js 。
- 为了方便查看更多信息，使用了 try-catch、onerror、onunhandledrejection 。

## <a name="eval"></a> EvalError
`EvalError` 已不再被 JavaScript 抛出，现在该对象为了保持兼容性存在。用下面的方式可以看到这种异常：
```js
try {
  throw new EvalError('Hello, EvalError');
} catch (e) {
  console.log(e instanceof EvalError); // true
  console.log(e.message);              // "Hello, EvalError"
  console.log(e.name);                 // "EvalError"
}
```

查一些资料说下面方式就会抛出该类型异常，但试了一下抛出的异常是 `TypeError` 。
```js
new eval();
```

## <a name="range"></a> RangeError
```js
const arr = new Array(-10)
```
![67-range-error][url-local-1]

## <a name="reference"></a> ReferenceError
```js
let a = undefinedVariable
```
![67-reference-error][url-local-2]

## <a name="syntax"></a> SyntaxError
```js
eval('hello syntax')
```
![67-syntax-error][url-local-3]

有些语法错误是无法捕获的，因为可能导致整个程序无法正常运行，不过这类型大多在编写阶段就会很容易发现。
```js
const a++;
```

## <a name="type"></a> TypeError
```js
const a = 'hell';
a.fun();
```
![67-type-error][url-local-4]

## <a name="uri"></a> URIError
```js
decodeURIComponent('%')
```
![67-uri-error][url-local-5]

## <a name="aggregate"></a> AggregateError
```js
Promise.any([
  Promise.reject(new Error("some error")),
]).catch(e => {
  throw e; // 这里抛出，让 onunhandledrejection 接收会有详细的异常信息
});
```
![67-aggregate-error][url-local-6]

## <a name="load"></a> 资源加载异常
常见的 `link`、`script`、`img` 标签加载异常都是这样类似的信息：

![67-static-error][url-local-7]

## <a name="api"></a> 接口请求异常
基础 `XMLHttpRequest` 示例：
```js
const xhr = new XMLHttpRequest();
xhr.open("GET", "http://localhost:6677/index");
xhr.onreadystatechange = function() {
  if (xhr.readyState == 4) {
    if (xhr.status == 200) {
      console.info('success')
    } else {
      console.info('xhr error：',xhr)
    }
  }
};
xhr.send();
```
![67-xhr-error][url-local-8]


基础 `fetch` 示例：
```js
fetch("http://localhost:6677/index").then((res) => {
  if (!res.ok) {
    throw res;
  }
}).catch((e) => {
  console.info('fetch error：',e);
})
```
![67-fetch-error][url-local-9]

## <a name="script"></a> Script error.
这个本地（浏览器直接文件路径访问）很容易出现，例如点击按钮的时候，抛出了一个异常，`onerror` 也捕获到了，但什么信息也没有：

![67-script-error][url-local-10]

换成 `try-catch` 捕获，有了一些信息：

![67-try-script-error][url-local-11]

这个应该是一个对象，用对象的形式打印一下：

![67-error-object][url-local-12]

这样就可以拿到相关的信息进行解析了，可参考 [TraceKit][url-github-1] 。

## 区分
看到上面的示例，有好几种形式的异常，进行处理的时候，区分判断的依据？

比较简单的做法，就是不用区分，既然都是异常，整个全都上报，在后台人工查看一样可以达到异常分析排查的目的。

在看 [sentry][url-github-2] 源码的时候，发现了另外一种思路：**根据异常的类型来区分**。

按照这个思路，接下来看看抛出的异常有那些类型，使用的主要方法是：

```js
function isInstanceOf(obj, base) {
  try {
      return obj instanceof base;
  } catch (e) {
      return false;
  }
}

function getType(value) {
  return Object.prototype.toString.call(value);
}

```






<div align="right"><a href="#index">Back to top :arrow_up:</a></div>

## <a name="reference"></a> 参考资料
- [Error mdn][url-mdn-1]

[url-mdn-1]:https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Error
[url-github-1]:https://github.com/csnover/TraceKit
[url-github-2]:https://github.com/getsentry/sentry
[url-blog-53]:https://github.com/XXHolic/blog/issues/53
[url-stackoverflow-1]:https://stackoverflow.com/questions/1382107/whats-a-good-way-to-extend-error-in-javascript

[url-local-1]:./images/67/range-error.png
[url-local-2]:./images/67/reference-error.png
[url-local-3]:./images/67/syntax-error.png
[url-local-4]:./images/67/type-error.png
[url-local-5]:./images/67/uri-error.png
[url-local-6]:./images/67/aggregate-error.png
[url-local-7]:./images/67/static-error.png
[url-local-8]:./images/67/xhr-error.png
[url-local-9]:./images/67/fetch-error.png
[url-local-10]:./images/67/script-error.png
[url-local-11]:./images/67/try-script-error.png
[url-local-12]:./images/67/error-object.png

<details>
<summary>:wastebasket:</summary>

实物与图案一致，不用参考。

![67-poster][url-local-poster]

</details>

[url-local-poster]:./images/67/fun.jpg
